spring:
  datasource:
    username: root
    password: my-secret-pw
    url: jdbc:mysql://localhost:6603/library
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    enabled: true
    out-of-order: true
    locations: classpath:db/migration
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false